name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: rafarfelipe
          outputs: dist/github-snake.svg

      - name: Fazer upload da cobrinha
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/github-snake.svg

      - name: Commitar e enviar para o branch output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan output
          git add -A
          git commit -m "Atualizando cobrinha"
          git push -f origin output
